### ISSUE TITLE
no exported names in the package

### ISSUE THREAD

**Issue by itchengguo** [leconio/AndroidCallGoDemo#1]
`
F:\Downloads\AndroidCallGoDemo-master\AndroidCallGoDemo-master\mobilego>gomobile bind -target=android mobile.go
gomobile: C:\Dev\Go\bin\gobind.exe -lang=go,java -outdir=C:\Users\cheng\AppData\Local\Temp\gomobile-work-353007155 failed: exit status 1
no exported names in the package "_/F_/Downloads/AndroidCallGoDemo-master/AndroidCallGoDemo-master/mobilego"
no exported names in the package "_/F_/Downloads/AndroidCallGoDemo-master/AndroidCallGoDemo-master/mobilego"
no exported names in the package "_/F_/Downloads/AndroidCallGoDemo-master/AndroidCallGoDemo-master/mobilego"
no exported names in the package "_/F_/Downloads/AndroidCallGoDemo-master/AndroidCallGoDemo-master/mobilego"

F:\Downloads\AndroidCallGoDemo-master\AndroidCallGoDemo-master\mobilego>`

不知道什么原因 在生成aar的时候 命令一直报这个错

**Comment by leconio** [comment]
代码比较老了，没有使用go mod。把它放到go path环境变量中，或者在这个目录初始化一个go mod。
```
go mod init gomobile
```

**Comment by itchengguo** [comment]
新手一个 完全模仿 我试试,感觉资料教程好少

**Comment by itchengguo** [comment]
感谢大佬 的指点 终于搞出来了
